version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Standard-Port für Ollama API
    volumes:
      - ollama_data:/root/.ollama  # Speichert Modelle & Daten persistent
    restart: unless-stopped

volumes:
  ollama_data: